support wakapi url or custom url, fix Manual date error
simonla/obsidian_waka_box pull request #2
Opened 2023-09-16 15:58 UTC by Wanxp

1. add support for wakapi server url
2. add support for custom wakapi or other wakatime-api-implement server url
3. fix bug: if not change anything in ManualModal , it will throw an error
4. add support if User input wrong date, it will throw an error

2023-09-16 19:38 UTC, simonla requested changes

2023-09-16 19:38 UTC, simonla commented on src/main.ts
> +			const result = await request(url);
'result' is assigned a value but never used

2023-09-16 19:38 UTC, simonla commented on src/main.ts
> +			new Notice(`WakaTime box: fail due to Invalid date`, 5000);
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

2023-09-16 19:38 UTC, simonla commented on src/main.ts
> +			.setDesc('Enter your own Wakapi API Url Or Other Server, Attention: "/api/compat/wakatime/v1" is required if you use your own wakapi server')
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

2023-09-16 19:38 UTC, simonla commented on src/main.ts
> +			.setName('WakaTime API Url Server Type')
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

2023-09-16 19:38 UTC, simonla commented on src/main.ts
> +			.setName('Test Connection')
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

2023-09-16 19:38 UTC, simonla commented on src/main.ts
> +			.setDesc('The WakaTime API Url being used now')
[Use sentence case in UI](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Use+sentence+case+in+UI)

2023-09-21 02:28 UTC, Wanxp commented on src/main.ts
> +			new Notice(`WakaTime box: fail due to Invalid date`, 5000);
result has removed

2023-09-21 02:29 UTC, Wanxp commented on src/main.ts
> +			.setDesc('Enter your own Wakapi API Url Or Other Server, Attention: "/api/compat/wakatime/v1" is required if you use your own wakapi server')
Desc change to `Enter your own Wakapi API url or other server, attention: "/api/compat/wakatime/v1" is required if you use your own Wakapi server'`

2023-09-21 02:30 UTC, Wanxp commented on src/main.ts
> +			.setName('WakaTime API Url Server Type')
Name change to `WakaTime API url server type`

2023-09-21 02:32 UTC, Wanxp commented on src/main.ts
> +			.setDesc('The WakaTime API Url being used now')
Desc changed to `The WakaTime API url being used now`

2023-09-21 02:32 UTC, Wanxp commented on src/main.ts
> +			.setName('Test Connection')
Name changed to `Test Connection`

2023-09-21 02:33 UTC, Wanxp commented on src/main.ts
> +			new Notice(`WakaTime box: fail due to Invalid date`, 5000);
Notice changed to `WakaTime box: fail due to invalid date`

2023-09-21 04:42 UTC, merged

2023-09-21 16:43 UTC, simonla commented
The `current server url` displayed in the settings sometimes does not match the `server type`. Especially after relaunch obsidian. So I temporarily rebase the master.